-- PostgreSQL insert query
START TRANSACTION; SET SEARCH_PATH TO cardshifter_stats; INSERT INTO card(version,name,flavor_text,effect_description,type,attack,health,sickness,attack_available) VALUES
(1,$$Spareparts$$,$$Cobbled together from whatever was lying around at the time.$$,$$null$$,$$Mech$$,0,1,1,1),
(1,$$Gyrodroid$$,$$A flying, spherical droid that shoots weak laser beams at nearby targets.$$,$$Ranged. Suffers no damage when attacking.$$,$$Mech$$,1,1,1,1),
(1,$$The Chopper$$,$$Looks like a flying circular blade with a sphere in the middle.$$,$$null$$,$$Mech$$,2,1,1,1),
(1,$$Shieldmech$$,$$A small, flying shield generator droid.$$,$$null$$,$$Mech$$,1,2,1,1),
(1,$$Humadroid$$,$$You might mistake it for a human, but it won’t mistake you for a mech.$$,$$null$$,$$Mech$$,3,3,1,1),
(1,$$Assasinatrix$$,$$Humanoid in form, except for two massive cannons in place of arms.$$,$$Ranged. Suffers no damage when attacking.$$,$$Mech$$,4,2,1,1),
(1,$$Fortimech$$,$$About the only place that a hume is safe during a firefight is inside one of these.$$,$$null$$,$$Mech$$,2,4,1,1),
(1,$$Scout Mech$$,$$The fastest mech on two legs. You don’t want to see the ones with four.$$,$$Rush. No cast sickness.$$,$$Mech$$,5,1,null,1),
(1,$$Supply Mech$$,$$Worth more than its weight in scrap, and it is pretty heavy.$$,$$Cannot attack.$$,$$Mech$$,0,5,1,null),
(1,$$Modleg Ambusher$$,$$Uses the legs of other bots to enhance its own speed.$$,$$Rush. No cast sickness.$$,$$Mech$$,5,3,null,1),
(1,$$Heavy Mech$$,$$The bigger they are, the harder they fall. Eventually.$$,$$null$$,$$Mech$$,3,6,1,1),
(1,$$Waste Runner$$,$$Armored and armed with superior arms.$$,$$null$$,$$Hume$$,4,4,1,1),
(1,$$Lost Soul$$,$$Echo of a powerful jacker that wanders the computerized wastes.$$,$$Steal 1 enemy Mech from the playing field.$$,$$Hume$$,2,5,null,1),
(1,$$Slacker Jacker$$,$$Spends all of his time jacked into the web.$$,$$All enemy Mechs have -1/-1 while this Hume is in play.$$,$$Hume$$,0,5,null,null),
(1,$$Spook$$,$$Hume that donated their human body to have their consciousness uploaded to the web.$$,$$All friendly Mechs have +1/+1 while this Hume is in play.$$,$$Bio$$,0,5,null,null),
(1,$$Conscript$$,$$He just signed up last week and he is very excited to fight.$$,$$null$$,$$Bio$$,2,2,1,1),
(1,$$Longshot$$,$$Eyes and reflexes augmented for maximum deadliness.$$,$$Ranged. Suffers no damage when attacking.$$,$$Bio$$,3,2,1,null),
(1,$$Bodyman$$,$$Strength augmented with mechanical musculature.$$,$$null$$,$$Bio$$,2,3,1,1),
(1,$$Vetter$$,$$A retired conscript with a desire to jack and make some quick creds.$$,$$null$$,$$Bio$$,3,3,1,1),
(1,$$Field Medic$$,$$Unsung hero responsible for keeping countless troops alive.$$,$$Heals the player for 1 health at the end of each turn$$,$$Bio$$,1,5,null,null),
(1,$$Wastelander$$,$$Spent his life learning the lessons of the wastelands.$$,$$null$$,$$Bio$$,4,4,1,1),
(1,$$Commander$$,$$A professional soldier for the government.$$,$$Rush. No cast sickness.$$,$$Bio$$,5,3,1,1),
(1,$$Cyberpimp$$,$$Supersized and heavily augmented.$$,$$null$$,$$Bio$$,3,5,1,1),
(1,$$Cyborg$$,$$He’s more machine than human now.$$,$$null$$,$$Bio$$,5,5,1,1),
(1,$$Web Boss$$,$$Leader of a gang that primarily operates on the web.$$,$$null$$,$$Bio$$,6,6,1,1),
(1,$$Inside Man$$,$$A government official with wider web control. Usually brings friends.$$,$$Cannot attack. Cast 2 Bodyman minions at no cost next to this unit.$$,$$Upgrade$$,2,6,1,null),
(1,$$Bionic Arms$$,$$These arms will give strength to even the most puny individual.$$,$$null$$,$$Upgrade$$,2,0,null,null),
(1,$$Body Armor$$,$$Steel-reinforced armor to absord damage from blows and shots.$$,$$null$$,$$Upgrade$$,0,2,null,null),
(1,$$Adrenalin Injection$$,$$An injection to increase speed and body function temporarily.$$,$$Rush. No cast sickness.$$,$$Upgrade$$,1,1,null,null),
(1,$$Reinforced Cranial Implants$$,$$Offers head protection as well as a slight increase in brain activity.$$,$$null$$,$$Upgrade$$,1,2,null,null),
(1,$$Steroid Implants$$,$$Intraveneous implants that feed the body for increased strength.$$,$$null$$,$$Upgrade$$,2,1,null,null),
(1,$$Cybernetic Arm Cannon$$,$$Replaces the forearm with a powerful firearm for massive damage.$$,$$Ranged. Suffers no damage when attacking.$$,$$Upgrade$$,3,0,null,null),
(1,$$Exoskeleton$$,$$This very invasive operation reinforces bone tissue with titanium.$$,$$null$$,$$Upgrade$$,0,3,null,null),
(1,$$Artificial Intelligence Implants$$,$$An advanced processor is connected to the subject's brain, replacing personality with extreme intelligence and reflexes.$$,$$null$$,$$Upgrade$$,2,2,null,null),
(1,$$Full-body Cybernetics$$,$$Most of the subject's body is converted to cybernetics, increasing strength and resilience substantially.$$,$$null$$,$$Spell$$,3,3,null,null),
(1,$$Dumpster$$,$$It is not unusual to find useful parts in garbage dumpsters in the city.$$,$$Gain 3 Scrap this turn only.$$,$$Spell$$,null,null,null,null),
(1,$$Scrapyard$$,$$Raid a scrapyard to find a plethora of useful robotic electronics.$$,$$Gain 5 Scrap this turn only.$$,$$Spell$$,null,null,null,null),
(1,$$Thievery$$,$$No need to sacrifice your own Mechs now, is there.$$,$$Steal 3 Scrap from opponent.$$,$$Spell$$,null,null,null,null),
(1,$$Pyromania$$,$$A bottle, a rag, and some fuel; perfect recipe to set a scrap pile ablaze.$$,$$Opponent loses all Scrap.$$,$$Spell$$,null,null,null,null),
(1,$$EMP$$,$$This nuclear device is highly damaging to electronic equipment.$$,$$Destroy all Mechs; players gain their Scrap value.$$,$$Spell$$,null,null,null,null),
(1,$$Head Shot$$,$$An accurate shot from a sniper is often enough to take down a person.$$,$$Destroy one Bio unit with 5 Health or less.$$,$$Spell$$,null,null,null,null),
(1,$$Immolate$$,$$When bullets are not enough, a massive flame can go a long way.$$,$$Destroy one Bio unit with 6 Health or more.$$,$$Spell$$,null,null,null,null),
(1,$$Downgrade$$,$$Modern warfare relies very heavily on cybernetics. Perhaps too heavily.$$,$$Remove all Upgrades from one Bio.$$,$$Spell$$,null,null,null,null),
(1,$$Spare Parts $$,$$A box of robotic parts you forgot you had kept in your warehouse.$$,$$The next Upgrade you play this turn costs 0 Scrap.$$,$$Spell$$,null,null,null,null),
(1,$$Firmware Upgrade$$,$$A new version of your Cybernetics Operating System is available.$$,$$Upgrade a Bio +2/+2 for a cost in Mana instead of Scrap.$$,$$Spell$$,2,2,null,null),
(1,$$CPU Upgrade $$,$$Specialized engineers have developed a powerful computer chip. For a price.$$,$$Upgrade a Mech +3/+3 for a cost in Scrap.$$,$$Spell$$,3,3,null,null),
(1,$$Magnetic Field$$,$$A strong magnetic field to keep all Mechs glued to the battlefield.$$,$$Opponent cannot scrap Mechs next turn.$$,$$Spell$$,null,null,null,null),
(1,$$Derelict$$,$$Low morale discourages new troops from joining the fight.$$,$$Opponent cannot play Bios next turn.$$,$$Spell$$,null,null,null,null),
(1,$$Hobble$$,$$Your lead engineer suffered an injury and needs time to heal.$$,$$Opponent cannot play any Upgrade next turn.$$,$$Spell$$,null,null,null,null),
(1,$$Rust Storm $$,$$Corrosion causes armor plates to crack and weaken.$$,$$Deal 2 damage to all Mechs.$$,$$Spell$$,null,null,null,null),
(1,$$Power Surge$$,$$A surge in the electrical system causes a strange, temporary boost in machines.$$,$$Owned Mechs gain 2 Attack this turn only.$$,$$Spell$$,null,null,null,null),
(1,$$Heat Shielding $$,$$Deploy a shield to protect mechanical units for a short time against incoming attacks.$$,$$Owned Mechs gain 2 Health during next opponent turn.$$,$$Spell$$,null,null,null,null),
(1,$$First Aid Kit$$,$$Mitigate combat wounds with this assortment of bandages and medicine.$$,$$Restore 3 health to the player.$$,$$Spell$$,null,null,null,null),
(1,$$Emergency Surgery$$,$$Expensive surgery to repair broken bones and patch up ripped flesh and muscle.$$,$$Restore 10 health to the player.$$,$$$$,null,null,null,null); COMMIT;
SELECT * FROM card;